[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "torch>=1.8"
]
build-backend = "setuptools.build_meta"

[project]
name = "fused_ssim"
version = "0.1.0"
dependencies = [
    "torch>=1.8"
]